#!/usr/bin/env bash

function main_prompt() {
	choices="App Launcher\nThemes Switcher\nLauncher Theme\nClipboard\nToggles\nClipboard Options\nPackages\nSystem Options"

	selection=$(echo -e "$choices" | rofi -dmenu -i -theme $HOME/.config/rofi/launcher/current_theme/theme.rasi)

	case "$selection" in
		"App Launcher")
			archemy-launch-rofi-launcher
			;;
		"Themes Switcher")
			archemy-launch-rofi-wallpaper
			;;
		"Launcher Theme")
			archemy-launch-rofi-select-launcher
			;;
		"Clipboard")
			archemy-launch-rofi-clipboard-history
			;;
		"Toggles")
			toggles_prompt
			;;
		"Clipboard Options")
			archemy-launch-rofi-clipboard-actions
			;;
		"Packages")
			package_prompt
			;;
		"System Options")
			pkill wlogout || wlogout -b 6
			;;
	esac
}

function package_prompt() {
	choices="Install package\nInstall AUR package\nRemove package\nUpdate packages"

	selection=$(echo -e "$choices" | rofi -dmenu -i -theme $HOME/.config/rofi/launcher/current_theme/theme.rasi)

	case "$selection" in
		"Install package")
			kitty --title="TUI app" -e archemy-pkg-install
			;;
		"Install AUR package")
			kitty --title="TUI app" -e archemy-pkg-aur-install
			;;
		"Remove package")
			kitty --title="TUI app" -e archemy-pkg-remove
			;;
		"Update packages")
			kitty --title="TUI app" -e archemy-pkg-update
			;;
	esac
}

function toggles_prompt() {
	choices="Night Lights\nDark/Light Theme\nKeyboard Layout\n"

	selection=$(echo -e "$choices" | rofi -dmenu -i -theme $HOME/.config/rofi/launcher/current_theme/theme.rasi)

	case "$selection" in
		"Night Lights")
			archemy-toggle-hyprsunset
			;;
		"Dark/Light Theme")
			archemy-toggle-theme
			;;
		"Keyboard Layout")
			archemy-manage-layout
			;;
	esac
}

main_prompt
